# Lab 7 - Recurrent Neural Networks
##### By. Liam Lowsley-Williams & Fernando Vazquez

## Business Understanding

### Introduction

### Motivations

### Objectives

### Evaluation

## Init

In [19]:
from distutils.version import LooseVersion
import warnings
import tensorflow as tf

# Check TensorFlow Version
assert LooseVersion(tf.__version__) >= LooseVersion('1.0'), 'Please use TensorFlow version 1.0 or newer.  You are using {}'.format(tf.__version__)
print('TensorFlow Version: {}'.format(tf.__version__))

# Check for a GPU
if not tf.test.gpu_device_name():
    warnings.warn('No GPU found. Please ensure you have installed TensorFlow correctly')
else:
    print('Default GPU Device: {}'.format(tf.test.gpu_device_name()))

TensorFlow Version: 2.0.0
Default GPU Device: /device:GPU:0


In [2]:
import keras
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential, Input, Model
from keras.layers import Dense
from keras.layers import SimpleRNN, LSTM
from keras.layers.embeddings import Embedding
from keras.callbacks import EarlyStopping

from sklearn import metrics as mt
from matplotlib import pyplot as plt
%matplotlib inline

import pickle
import numpy as np
import pandas as pd

# graph visualization
from IPython.display import SVG
from keras.utils.vis_utils import model_to_dot

keras.__version__

Using TensorFlow backend.


'2.3.1'

## Data Preperation

In [3]:
data = pd.read_csv("reviews.csv")
data

ReviewTitle  \
0                 Honest review of an edm music lover\n   
1                 Unreliable earphones with high cost\n   
2                            Really good and durable.\n   
3                     stopped working in just 14 days\n   
4      Just Awesome Wireless Headphone under 1000...😉\n   
...                                                 ...   
14332                                            Good\n   
14333                                 Amazing Product\n   
14334                                         Not bad\n   
14335                                  a good product\n   
14336           Average headphones , n overrated name\n   

                                              ReviewBody  ReviewStar  \
0      No doubt it has a great bass and to a great ex...           3   
1      This  earphones are unreliable, i bought it be...           1   
2      i bought itfor 999,I purchased it second time,...           4   
3      Its sound quality is adorable. overall it was ...           1   
4      Its Awesome... Good sound quality & 8-9 hrs ba...           5   
...                                                  ...         ...   
14332                                             Good\n           4   
14333             An amazing product but a bit costly.\n           5   
14334                                            Sound\n           1   
14335  the sound is good battery life is good but the...           5   
14336  M writing this review after using for almost 7...           1   

                Product  
0      boAt Rockerz 255  
1      boAt Rockerz 255  
2      boAt Rockerz 255  
3      boAt Rockerz 255  
4      boAt Rockerz 255  
...                 ...  
14332        JBL T110BT  
14333        JBL T110BT  
14334        JBL T110BT  
14335        JBL T110BT  
14336        JBL T110BT  

[14337 rows x 4 columns]

In [4]:
data_title = data["ReviewTitle"]
data_body = data["ReviewBody"]
y = data["ReviewStar"]

In [5]:
X_data = data["ReviewTitle"].map(str) + " " + data["ReviewBody"]
X_data

0        Honest review of an edm music lover\n No doubt...
1        Unreliable earphones with high cost\n This  ea...
2        Really good and durable.\n i bought itfor 999,...
3        stopped working in just 14 days\n Its sound qu...
4        Just Awesome Wireless Headphone under 1000...😉...
                               ...                        
14332                                        Good\n Good\n
14333    Amazing Product\n An amazing product but a bit...
14334                                    Not bad\n Sound\n
14335    a good product\n the sound is good battery lif...
14336    Average headphones , n overrated name\n M writ...
Length: 14337, dtype: object

In [8]:
X_data.map(lambda x: len(x)).max()

5074

In [40]:
%%time
NUM_TOP_WORDS = None
MAX_ART_LEN = 1000 # maximum and minimum number of words
NUM_CLASSES = 5

tokenizer = Tokenizer(num_words=NUM_TOP_WORDS)
tokenizer.fit_on_texts(X_data)
sequences = tokenizer.texts_to_sequences(X_data)

word_index = tokenizer.word_index
NUM_TOP_WORDS = len(word_index) if NUM_TOP_WORDS==None else NUM_TOP_WORDS
top_words = min((len(word_index),NUM_TOP_WORDS))
print('Found %s unique tokens. Distilled to %d top words.' % (len(word_index),top_words))

X = pad_sequences(sequences, maxlen=MAX_ART_LEN)
# X = pad_sequences(sequences)


y_ohe = keras.utils.to_categorical(y)
print('Shape of data tensor:', X.shape)
print('Shape of label tensor:', y_ohe.shape)
print(np.max(X))

Found 12156 unique tokens. Distilled to 12156 top words.
Shape of data tensor: (14337, 1000)
Shape of label tensor: (14337, 6)
12156
Wall time: 684 ms


In [27]:
X

array([[   0,    0,    0, ...,  149,   37,  133],
       [   0,    0,    0, ..., 1634,    9,  301],
       [   0,    0,    0, ...,  150,   31,   45],
       ...,
       [   0,    0,    0, ...,   11,   70,    6],
       [   0,    0,    0, ...,   18,    3,    9],
       [   0,    0,    0, ...,   82,  298,  208]])

In [41]:
from sklearn.model_selection import train_test_split
# Split it into train / test subsets
X_train, X_test, y_train, y_test = train_test_split(X, y_ohe, test_size=0.2,
                                                              stratify=y, 
                                                              random_state=42)

# get rid of empty column at begginning
y_train = y_train[:,1:]
y_test = y_test[:,1:]

print(X_train.shape,y_train.shape)
print(X_test.shape,y_test.shape)
print(np.sum(y_train,axis=0))
print(np.sum(y_test,axis=0))

(11469, 1000) (11469, 5)
(2868, 1000) (2868, 5)
[1994.  751. 1203. 2551. 4970.]
[ 499.  188.  300.  638. 1243.]


## Evaluation

### Model 1

In [ ]:
max_review_length = 927
EMBED_SIZE = 50
input_holder = Input(shape=(X_train.shape[1], ))
input_embed = Embedding((np.max(X_train)+1), # input dimension (max int of OHE)
                EMBED_SIZE, # output dimension size
                input_length=max_review_length)(input_holder) # number of words in each sequence


x = SimpleRNN(25,dropout=0.2, recurrent_dropout=0.2)(input_embed)
x = Dense(NUM_CLASSES, activation='sigmoid')(x)
rnn=Model(inputs=input_holder,outputs=x)
rnn.compile(loss='categorical_crossentropy', 
            optimizer='rmsprop', 
            metrics=['accuracy'])

rnn.summary()

In [ ]:
rnn.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=3, batch_size=64)

In [ ]:
rnn.fit(X_train, y_train, 
        epochs=15, 
        batch_size=64, 
        validation_data=(X_test, y_test), 
        callbacks=[EarlyStopping(monitor='val_loss', patience=2)]
       )

In [ ]:
rnn.save_weights('model_1_weights.h5')

### Model 2

In [26]:
%%time
# NUM_TOP_WORDS = None
# tokenizer = Tokenizer(num_words=NUM_TOP_WORDS)
# word_index = tokenizer.word_index

EMBED_SIZE = 100
# the embed size should match the file you load glove from
embeddings_index = {}
f = open('./glove/glove.6B.100d.txt', encoding="utf8")
# save key/array pairs of the embeddings
#  the key of the dictionary is the word, the array is the embedding
for line in f:
    values = line.split()
    word = values[0]
    coefs = np.asarray(values[1:], dtype='float32')
    embeddings_index[word] = coefs
f.close()

print('Found %s word vectors.' % len(embeddings_index))

# now fill in the matrix, using the ordering from the
#  keras word tokenizer from before
embedding_matrix = np.zeros((len(word_index) + 1, EMBED_SIZE))
for word, i in word_index.items():
    embedding_vector = embeddings_index.get(word)
    if embedding_vector is not None:
        # words not found in embedding index will be all-zeros.
        embedding_matrix[i] = embedding_vector

print(embedding_matrix.shape)


Found 400000 word vectors.
(12157, 100)
Wall time: 10.9 s


In [ ]:
len(embeddings_index)

In [43]:
MAX_ART_LEN

1000

In [42]:
embedding_layer = Embedding(len(word_index) + 1,
                            EMBED_SIZE,
                            weights=[embedding_matrix],
                            input_length=MAX_ART_LEN,
                            trainable=False)

In [38]:
rnn = Sequential()
rnn.add(embedding_layer)
rnn.add(LSTM(100,dropout=0.2, recurrent_dropout=0.2))
rnn.add(Dense(NUM_CLASSES, activation='sigmoid'))
rnn.compile(loss='categorical_crossentropy', 
              optimizer='rmsprop', 
              metrics=['accuracy'])
print(rnn.summary())

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, None, 100)         1215700   
_________________________________________________________________
lstm_2 (LSTM)                (None, 100)               80400     
_________________________________________________________________
dense_2 (Dense)              (None, 5)                 505       
Total params: 1,296,605
Trainable params: 80,905
Non-trainable params: 1,215,700
_________________________________________________________________
None


In [44]:
rnn.fit(X_train, 
        y_train, 
        epochs=15, 
        batch_size=64,
        validation_data=(X_test, y_test),
        callbacks=[EarlyStopping(monitor='val_loss', patience=2)]
       )

Train on 11469 samples, validate on 2868 samples
Epoch 1/15
11469/11469 [==============================] - 105s 9ms/step - loss: 0.8867 - accuracy: 0.6291 - val_loss: 0.9367 - val_accuracy: 0.6231
Epoch 2/15
11469/11469 [==============================] - 105s 9ms/step - loss: 0.8752 - accuracy: 0.6334 - val_loss: 0.9221 - val_accuracy: 0.6231
Epoch 3/15
11469/11469 [==============================] - 104s 9ms/step - loss: 0.8632 - accuracy: 0.6389 - val_loss: 0.9103 - val_accuracy: 0.6266
Epoch 4/15
11469/11469 [==============================] - 104s 9ms/step - loss: 0.8514 - accuracy: 0.6433 - val_loss: 0.9146 - val_accuracy: 0.6273
Epoch 5/15
11469/11469 [==============================] - 104s 9ms/step - loss: 0.8357 - accuracy: 0.6538 - val_loss: 0.9250 - val_accuracy: 0.6311


In [45]:
rnn.fit(X_train, 
        y_train, 
        epochs=15, 
        batch_size=64,
        validation_data=(X_test, y_test),
        callbacks=[EarlyStopping(monitor='val_loss', patience=3)]
       )

Train on 11469 samples, validate on 2868 samples
Epoch 1/15
11469/11469 [==============================] - 106s 9ms/step - loss: 0.8303 - accuracy: 0.6525 - val_loss: 0.9156 - val_accuracy: 0.6325
Epoch 2/15
11469/11469 [==============================] - 106s 9ms/step - loss: 0.8147 - accuracy: 0.6613 - val_loss: 0.9140 - val_accuracy: 0.6381
Epoch 3/15
11469/11469 [==============================] - 106s 9ms/step - loss: 0.8058 - accuracy: 0.6637 - val_loss: 0.9140 - val_accuracy: 0.6370
Epoch 4/15
11469/11469 [==============================] - 105s 9ms/step - loss: 0.7980 - accuracy: 0.6663 - val_loss: 0.9300 - val_accuracy: 0.6412
Epoch 5/15
11469/11469 [==============================] - 105s 9ms/step - loss: 0.7886 - accuracy: 0.6773 - val_loss: 0.9149 - val_accuracy: 0.6370
